apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-oom
  namespace: stress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stress-oom
  template:
    metadata:
      labels:
        app: stress-oom
    spec:
      containers:
        - name: stress
          image: polinux/stress:1.0.4
          command: ["stress"]
          args: ["--vm", "1", "--vm-bytes", "95M", "--timeout", "3600s"]
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
